name: Python Unit Test Workflow

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  unit-tests:
    runs-on: self-hosted  # Use a self-hosted runner
    strategy:
      matrix:
        os: [windows-latest]  # Specify the operating systems you want to run on

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Run Unit Tests with JUnit XML Report
        run: |
          pytest --junitxml=pytest-report.xml
          # Add other test options or commands as needed

      - name: Print Current Directory and Files
        run: |
          pwd
          ls -R

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            pytest-report.xml
            # Add other files or directories as needed
